import { useNavigate } from 'react-router-dom'
import { COLORS } from '../lib/colors'
import { useIsMobile } from '../hooks/useIsMobile'

const GITHUB_URL = 'https://github.com/jacob-beattie/VEXR'

const features = [
  {
    icon: '∿',
    color: COLORS.purple,
    title: 'PMC Fitness Engine',
    desc: 'Full TrainingPeaks-model CTL/ATL/TSB via exponential weighted moving averages. 42-day fitness constant, 7-day fatigue constant — calculated client-side from raw TSS history.',
  },
  {
    icon: '✦',
    color: COLORS.accent,
    title: 'AI Coaching',
    desc: 'Weekly briefings generated by the Claude API (claude-sonnet-4-6). 24h caching in Supabase, force-refresh override, up to 9 entries of history. Edge Function with manual ES256 JWT auth.',
  },
  {
    icon: '◎',
    color: COLORS.orange,
    title: 'Strava Integration',
    desc: 'Full OAuth 2.0 flow with token exchange and auto-refresh. Syncs on session start, deduplicates by strava_activity_id, per-user rate limiting via api_rate_limits table.',
  },
  {
    icon: '≡',
    color: COLORS.green,
    title: 'Training Plan Import',
    desc: 'PDF or text upload → Claude AI parsing → conflict detection → 3-step review modal → writes to training_plans, training_sessions, and workouts with cascade deletes.',
  },
  {
    icon: '⊞',
    color: COLORS.accent,
    title: 'Drag & Drop Calendar',
    desc: '@dnd-kit powered rescheduling in both month and week views. Planned vs completed states, mobile DayBottomSheet, click-to-log on empty cells.',
  },
  {
    icon: '◈',
    color: COLORS.purple,
    title: 'Structured Workout Builder',
    desc: 'Interval block editor (Warmup / Interval / Rest / Cooldown) with drag-to-reorder, auto-calculated TSS and duration, per-block intensity hints stored as JSONB.',
  },
]

const techStack = [
  'React 18', 'TypeScript', 'Vite', 'Supabase', 'Recharts',
  'Claude API', 'Strava API', '@dnd-kit', 'pdfjs-dist',
]

function FeatureCard({ icon, color, title, desc, isMobile }: {
  icon: string; color: string; title: string; desc: string; isMobile: boolean
}) {
  return (
    <div style={{
      background: COLORS.card,
      borderTop: `1px solid ${COLORS.border}`,
      borderRight: `1px solid ${COLORS.border}`,
      borderBottom: `1px solid ${COLORS.border}`,
      borderLeft: `3px solid ${color}`,
      borderRadius: 12,
      padding: isMobile ? '20px 18px' : '24px 22px',
      display: 'flex',
      flexDirection: 'column',
      gap: 12,
    }}>
      <div style={{
        width: 36, height: 36, borderRadius: 9,
        background: `${color}18`,
        display: 'flex', alignItems: 'center', justifyContent: 'center',
        fontSize: 17, color,
        flexShrink: 0,
      }}>
        {icon}
      </div>
      <div>
        <div style={{ fontSize: 15, fontWeight: 700, color: COLORS.text, marginBottom: 7 }}>
          {title}
        </div>
        <div style={{ fontSize: 13, color: COLORS.muted, lineHeight: 1.65 }}>
          {desc}
        </div>
      </div>
    </div>
  )
}

function StatMockup() {
  const stats = [
    { label: 'CTL', value: '68', sub: 'Fitness', color: COLORS.purple },
    { label: 'ATL', value: '74', sub: 'Fatigue', color: COLORS.orange },
    { label: 'TSB', value: '-6', sub: 'Form', color: COLORS.danger },
    { label: 'TSS', value: '342', sub: 'This week', color: COLORS.accent },
  ]
  return (
    <div style={{
      background: COLORS.card,
      borderTop: `1px solid ${COLORS.border}`,
      borderRight: `1px solid ${COLORS.border}`,
      borderBottom: `1px solid ${COLORS.border}`,
      borderLeft: `1px solid ${COLORS.border}`,
      borderRadius: 10,
      padding: '18px 24px',
      display: 'flex',
      gap: 0,
    }}>
      {stats.map((s, i) => (
        <div key={s.label} style={{ flex: 1, textAlign: 'center', position: 'relative' }}>
          {i > 0 && (
            <div style={{
              position: 'absolute', left: 0, top: '10%', bottom: '10%',
              width: 1, background: COLORS.border,
            }} />
          )}
          <div style={{ fontSize: 10, color: COLORS.muted, fontWeight: 700, letterSpacing: '0.08em', textTransform: 'uppercase', marginBottom: 6 }}>
            {s.label}
          </div>
          <div style={{ fontSize: 26, fontWeight: 900, color: s.color, fontFamily: 'DM Mono, monospace', lineHeight: 1 }}>
            {s.value}
          </div>
          <div style={{ fontSize: 11, color: COLORS.muted, marginTop: 5 }}>{s.sub}</div>
        </div>
      ))}
    </div>
  )
}

function ChartMockup() {
  const w = 400; const h = 90
  const ctl = [38, 42, 45, 50, 55, 58, 62, 68]
  const atl  = [30, 55, 48, 72, 60, 70, 80, 74]
  const max  = 90
  const toPath = (vals: number[]) =>
    vals.map((v, i) => `${i === 0 ? 'M' : 'L'}${(i / (vals.length - 1)) * w},${h - (v / max) * h}`).join(' ')

  return (
    <div style={{
      background: COLORS.card,
      borderTop: `1px solid ${COLORS.border}`,
      borderRight: `1px solid ${COLORS.border}`,
      borderBottom: `1px solid ${COLORS.border}`,
      borderLeft: `1px solid ${COLORS.border}`,
      borderRadius: 10,
      padding: '16px 20px',
    }}>
      <div style={{ fontSize: 11, color: COLORS.muted, fontWeight: 700, letterSpacing: '0.08em', textTransform: 'uppercase', marginBottom: 10 }}>
        Fitness · Fatigue · Form
      </div>
      <svg viewBox={`0 0 ${w} ${h}`} style={{ width: '100%', height: 'auto', display: 'block' }} preserveAspectRatio="none">
        <defs>
          <linearGradient id="lp-ctl" x1="0" y1="0" x2="0" y2="1">
            <stop offset="0%" stopColor={COLORS.purple} stopOpacity="0.2" />
            <stop offset="100%" stopColor={COLORS.purple} stopOpacity="0.01" />
          </linearGradient>
          <linearGradient id="lp-atl" x1="0" y1="0" x2="0" y2="1">
            <stop offset="0%" stopColor={COLORS.orange} stopOpacity="0.15" />
            <stop offset="100%" stopColor={COLORS.orange} stopOpacity="0.01" />
          </linearGradient>
        </defs>
        <path d={`${toPath(ctl)} L${w},${h} L0,${h} Z`} fill="url(#lp-ctl)" />
        <path d={toPath(ctl)} fill="none" stroke={COLORS.purple} strokeWidth="2" />
        <path d={`${toPath(atl)} L${w},${h} L0,${h} Z`} fill="url(#lp-atl)" />
        <path d={toPath(atl)} fill="none" stroke={COLORS.orange} strokeWidth="2" />
      </svg>
      <div style={{ display: 'flex', gap: 16, marginTop: 10 }}>
        {[['CTL', COLORS.purple], ['ATL', COLORS.orange], ['TSB', COLORS.green]].map(([label, color]) => (
          <div key={label} style={{ display: 'flex', alignItems: 'center', gap: 5 }}>
            <div style={{ width: 7, height: 7, borderRadius: '50%', background: color }} />
            <span style={{ fontSize: 11, color: COLORS.muted }}>{label}</span>
          </div>
        ))}
      </div>
    </div>
  )
}

export function Landing() {
  const navigate = useNavigate()
  const isMobile = useIsMobile()

  return (
    <div style={{
      minHeight: '100vh',
      background: COLORS.bg,
      color: COLORS.text,
      fontFamily: "'Inter', 'Helvetica Neue', sans-serif",
      overflowX: 'hidden',
    }}>

      {/* Nav */}
      <nav style={{
        display: 'flex', alignItems: 'center', justifyContent: 'space-between',
        padding: isMobile ? '14px 20px' : '16px 48px',
        borderBottom: `1px solid ${COLORS.border}`,
        position: 'sticky', top: 0, zIndex: 10,
        background: `${COLORS.bg}f0`,
        backdropFilter: 'blur(10px)',
      }}>
        <span style={{
          fontSize: 20, fontWeight: 900, letterSpacing: '-0.04em',
          color: COLORS.text,
        }}>
          VE<span style={{ color: COLORS.accent }}>X</span>R
        </span>
        <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
          <a
            href={GITHUB_URL}
            target="_blank"
            rel="noreferrer"
            style={{
              fontSize: 13, fontWeight: 600, color: COLORS.muted,
              textDecoration: 'none',
              padding: '6px 14px',
              borderTop: `1px solid ${COLORS.border}`,
              borderRight: `1px solid ${COLORS.border}`,
              borderBottom: `1px solid ${COLORS.border}`,
              borderLeft: `1px solid ${COLORS.border}`,
              borderRadius: 8,
            }}
          >
            GitHub ↗
          </a>
          <button
            onClick={() => navigate('/login')}
            style={{
              fontSize: 13, fontWeight: 700, color: '#fff',
              background: COLORS.accent,
              border: 'none',
              borderRadius: 8,
              padding: '6px 16px',
              cursor: 'pointer',
            }}
          >
            Try the App →
          </button>
        </div>
      </nav>

      {/* Hero */}
      <section style={{
        padding: isMobile ? '56px 24px 40px' : '88px 48px 64px',
        maxWidth: 860,
        margin: '0 auto',
        textAlign: 'center',
      }}>
        <div style={{
          display: 'inline-flex', alignItems: 'center', gap: 6,
          fontSize: 11, fontWeight: 700, letterSpacing: '0.1em',
          textTransform: 'uppercase', color: COLORS.accent,
          background: COLORS.accentDim,
          borderTop: `1px solid ${COLORS.accent}40`,
          borderRight: `1px solid ${COLORS.accent}40`,
          borderBottom: `1px solid ${COLORS.accent}40`,
          borderLeft: `1px solid ${COLORS.accent}40`,
          borderRadius: 20,
          padding: '4px 14px',
          marginBottom: 28,
        }}>
          Portfolio Project · Full-Stack SaaS
        </div>

        <h1 style={{
          fontSize: isMobile ? 36 : 60,
          fontWeight: 900,
          letterSpacing: '-0.04em',
          lineHeight: 1.08,
          margin: '0 0 22px',
          color: COLORS.text,
        }}>
          Endurance training analytics,{' '}
          <span style={{ color: COLORS.accent }}>built from scratch</span>
        </h1>

        <p style={{
          fontSize: isMobile ? 15 : 17,
          color: COLORS.muted,
          lineHeight: 1.7,
          maxWidth: 580,
          margin: '0 auto 36px',
        }}>
          Vexr is a full-stack TrainingPeaks-style platform for triathletes — with a PMC fitness engine, AI coaching via Claude, Strava OAuth sync, structured workout builder, and PDF training plan import.
        </p>

        <div style={{ display: 'flex', gap: 10, justifyContent: 'center', flexWrap: 'wrap', marginBottom: 40 }}>
          <button
            onClick={() => navigate('/login')}
            style={{
              padding: '11px 26px', fontSize: 14, fontWeight: 700,
              background: COLORS.accent, color: '#fff',
              border: 'none', borderRadius: 9, cursor: 'pointer',
            }}
          >
            Try the App →
          </button>
          <a
            href={GITHUB_URL}
            target="_blank"
            rel="noreferrer"
            style={{
              padding: '11px 26px', fontSize: 14, fontWeight: 700,
              background: 'transparent', color: COLORS.text,
              borderTop: `1px solid ${COLORS.border}`,
              borderRight: `1px solid ${COLORS.border}`,
              borderBottom: `1px solid ${COLORS.border}`,
              borderLeft: `1px solid ${COLORS.border}`,
              borderRadius: 9, cursor: 'pointer',
              textDecoration: 'none', display: 'inline-block',
            }}
          >
            View Source ↗
          </a>
        </div>

        {/* Tech stack pills */}
        <div style={{ display: 'flex', gap: 7, justifyContent: 'center', flexWrap: 'wrap' }}>
          {techStack.map(t => (
            <span key={t} style={{
              fontSize: 12, fontWeight: 500, color: COLORS.muted,
              background: COLORS.surface,
              borderTop: `1px solid ${COLORS.border}`,
              borderRight: `1px solid ${COLORS.border}`,
              borderBottom: `1px solid ${COLORS.border}`,
              borderLeft: `1px solid ${COLORS.border}`,
              borderRadius: 6,
              padding: '3px 10px',
            }}>
              {t}
            </span>
          ))}
        </div>
      </section>

      {/* Dashboard preview */}
      <section style={{
        padding: isMobile ? '0 20px 56px' : '0 48px 72px',
        maxWidth: 800,
        margin: '0 auto',
      }}>
        <div style={{
          background: COLORS.surface,
          borderTop: `1px solid ${COLORS.border}`,
          borderRight: `1px solid ${COLORS.border}`,
          borderBottom: `1px solid ${COLORS.border}`,
          borderLeft: `1px solid ${COLORS.border}`,
          borderRadius: 16,
          padding: 16,
          display: 'flex',
          flexDirection: 'column',
          gap: 10,
        }}>
          {/* Fake browser chrome */}
          <div style={{ display: 'flex', alignItems: 'center', gap: 6, paddingBottom: 10, borderBottom: `1px solid ${COLORS.border}`, marginBottom: 4 }}>
            {['#ff5f57', '#febc2e', '#28c840'].map(c => (
              <div key={c} style={{ width: 10, height: 10, borderRadius: '50%', background: c }} />
            ))}
            <div style={{
              flex: 1, height: 22, borderRadius: 5,
              background: COLORS.subtle,
              display: 'flex', alignItems: 'center', justifyContent: 'center',
              fontSize: 11, color: COLORS.muted, fontFamily: 'DM Mono, monospace',
            }}>
              vexr.app/dashboard
            </div>
          </div>
          <StatMockup />
          <ChartMockup />
        </div>
        <div style={{ textAlign: 'center', marginTop: 10 }}>
          <span style={{ fontSize: 12, color: COLORS.muted }}>
            Metrics rendered from real Supabase data
          </span>
        </div>
      </section>

      {/* Features */}
      <section style={{
        padding: isMobile ? '48px 20px' : '72px 48px',
        maxWidth: 1100,
        margin: '0 auto',
      }}>
        <div style={{ textAlign: 'center', marginBottom: 44 }}>
          <div style={{ fontSize: 11, color: COLORS.muted, fontWeight: 700, letterSpacing: '0.1em', textTransform: 'uppercase', marginBottom: 10 }}>
            What's inside
          </div>
          <h2 style={{ fontSize: isMobile ? 26 : 36, fontWeight: 900, letterSpacing: '-0.03em', margin: 0, color: COLORS.text }}>
            Every feature built end-to-end
          </h2>
        </div>

        <div style={{
          display: 'grid',
          gridTemplateColumns: isMobile ? '1fr' : 'repeat(3, 1fr)',
          gap: 14,
        }}>
          {features.map(f => (
            <FeatureCard key={f.title} {...f} isMobile={isMobile} />
          ))}
        </div>
      </section>

      {/* Architecture callout */}
      <section style={{
        padding: isMobile ? '48px 20px' : '72px 48px',
        maxWidth: 860,
        margin: '0 auto',
      }}>
        <div style={{
          background: COLORS.surface,
          borderTop: `1px solid ${COLORS.border}`,
          borderRight: `1px solid ${COLORS.border}`,
          borderBottom: `1px solid ${COLORS.border}`,
          borderLeft: `1px solid ${COLORS.border}`,
          borderRadius: 16,
          padding: isMobile ? '28px 24px' : '40px 44px',
        }}>
          <div style={{ fontSize: 11, color: COLORS.muted, fontWeight: 700, letterSpacing: '0.1em', textTransform: 'uppercase', marginBottom: 14 }}>
            Architecture
          </div>
          <h3 style={{ fontSize: isMobile ? 22 : 28, fontWeight: 800, letterSpacing: '-0.03em', margin: '0 0 20px', color: COLORS.text }}>
            Production-quality patterns throughout
          </h3>
          <div style={{ fontSize: 14, color: COLORS.muted, lineHeight: 1.75, display: 'flex', flexDirection: 'column', gap: 12 }}>
            {[
              "Supabase Edge Functions with manual ES256 JWT verification — Supabase's runtime only supports HS256, so auth is enforced inside each handler via Bearer token check + supabase.auth.getUser().",
              'Code-split React with lazy() + Suspense across all pages. Vite manualChunks splits vendor-react, vendor-supabase, and vendor-charts. Main bundle reduced from 962KB → 33KB.',
              'Full RLS on every table. React Error Boundary at root. Per-user rate limiting on Strava and Anthropic edge functions. 30s AbortController timeouts on all external fetch calls.',
              'Mobile-first responsive layout using a JS-driven useIsMobile hook — no media queries, no Tailwind. Every breakpoint handled via inline styles.',
            ].map((point, i) => (
              <div key={i} style={{ display: 'flex', gap: 12, alignItems: 'flex-start' }}>
                <span style={{ color: COLORS.accent, flexShrink: 0, fontWeight: 700, marginTop: 1 }}>→</span>
                <span>{point}</span>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA */}
      <section style={{
        padding: isMobile ? '48px 20px 72px' : '72px 48px 96px',
        textAlign: 'center',
      }}>
        <h2 style={{ fontSize: isMobile ? 26 : 36, fontWeight: 900, letterSpacing: '-0.03em', margin: '0 0 14px', color: COLORS.text }}>
          See it in action
        </h2>
        <p style={{ fontSize: 15, color: COLORS.muted, margin: '0 0 30px' }}>
          Sign up with an email address and start logging workouts instantly.
        </p>
        <div style={{ display: 'flex', gap: 10, justifyContent: 'center', flexWrap: 'wrap' }}>
          <button
            onClick={() => navigate('/signup')}
            style={{
              padding: '11px 30px', fontSize: 14, fontWeight: 700,
              background: COLORS.accent, color: '#fff',
              border: 'none', borderRadius: 9, cursor: 'pointer',
            }}
          >
            Create Account →
          </button>
          <button
            onClick={() => navigate('/login')}
            style={{
              padding: '11px 30px', fontSize: 14, fontWeight: 700,
              background: 'transparent', color: COLORS.text,
              borderTop: `1px solid ${COLORS.border}`,
              borderRight: `1px solid ${COLORS.border}`,
              borderBottom: `1px solid ${COLORS.border}`,
              borderLeft: `1px solid ${COLORS.border}`,
              borderRadius: 9, cursor: 'pointer',
            }}
          >
            Sign In
          </button>
        </div>
      </section>

      {/* Footer */}
      <footer style={{
        borderTop: `1px solid ${COLORS.border}`,
        padding: isMobile ? '20px 20px' : '24px 48px',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
        flexWrap: 'wrap',
        gap: 10,
        background: COLORS.surface,
      }}>
        <span style={{ fontSize: 13, color: COLORS.muted }}>
          Built by <span style={{ color: COLORS.text, fontWeight: 600 }}>Jacob Beattie</span>
        </span>
        <div style={{ display: 'flex', gap: 20, alignItems: 'center' }}>
          <a href={GITHUB_URL} target="_blank" rel="noreferrer"
            style={{ fontSize: 13, color: COLORS.muted, textDecoration: 'none' }}>
            GitHub ↗
          </a>
          <button
            onClick={() => navigate('/login')}
            style={{ fontSize: 13, color: COLORS.accent, background: 'none', border: 'none', cursor: 'pointer', fontWeight: 700, padding: 0 }}
          >
            Try the App →
          </button>
        </div>
      </footer>
    </div>
  )
}
