import { useNavigate } from 'react-router-dom'
import { COLORS } from '../lib/colors'
import { useIsMobile } from '../hooks/useIsMobile'

const GITHUB_URL = 'https://github.com/jacob-beattie/VEXR'

const features = [
  {
    icon: '∿',
    color: COLORS.purple,
    title: 'PMC Fitness Engine',
    desc: 'Full TrainingPeaks-model CTL/ATL/TSB via exponential weighted moving averages. 42-day fitness constant, 7-day fatigue constant — all calculated client-side from raw TSS history.',
  },
  {
    icon: '✦',
    color: COLORS.accent,
    title: 'AI Coaching',
    desc: 'Weekly briefings generated by the Claude API (claude-sonnet-4-6). 24h caching in Supabase, force-refresh override, accumulates history up to 9 entries. Supabase Edge Function with manual ES256 JWT auth.',
  },
  {
    icon: '◎',
    color: COLORS.orange,
    title: 'Strava Integration',
    desc: 'Full OAuth 2.0 flow with token exchange and refresh. Auto-syncs on session start, deduplicates by strava_activity_id, per-user rate limiting via api_rate_limits table.',
  },
  {
    icon: '≡',
    color: COLORS.green,
    title: 'Training Plan Import',
    desc: 'PDF or text upload → Claude AI parsing → conflict detection against existing calendar → 3-step review modal → writes to training_plans, training_sessions, and workouts with cascade deletes.',
  },
  {
    icon: '⊞',
    color: COLORS.accent,
    title: 'Drag & Drop Calendar',
    desc: '@dnd-kit powered rescheduling in both month and week views. Distinguishes planned vs completed workouts, mobile-optimised DayBottomSheet, click-to-log on empty cells.',
  },
  {
    icon: '◈',
    color: COLORS.purple,
    title: 'Structured Workout Builder',
    desc: 'Interval block editor (Warmup / Interval / Rest / Cooldown) with drag-to-reorder, auto-calculated TSS and duration, per-block intensity hints, stored as JSONB in Supabase.',
  },
]

const techStack = [
  'React 18', 'TypeScript', 'Vite', 'Supabase', 'Recharts',
  'Claude API', 'Strava API', '@dnd-kit', 'pdfjs-dist',
]

function FeatureCard({ icon, color, title, desc, isMobile }: {
  icon: string; color: string; title: string; desc: string; isMobile: boolean
}) {
  return (
    <div style={{
      background: COLORS.surface,
      borderTop: `1px solid ${COLORS.border}`,
      borderRight: `1px solid ${COLORS.border}`,
      borderBottom: `1px solid ${COLORS.border}`,
      borderLeft: `3px solid ${color}`,
      borderRadius: 12,
      padding: isMobile ? '20px 18px' : '24px 22px',
      display: 'flex',
      flexDirection: 'column',
      gap: 12,
    }}>
      <div style={{
        width: 38, height: 38, borderRadius: 10,
        background: `${color}18`,
        display: 'flex', alignItems: 'center', justifyContent: 'center',
        fontSize: 18, color,
        flexShrink: 0,
      }}>
        {icon}
      </div>
      <div>
        <div style={{ fontSize: 15, fontWeight: 700, color: COLORS.text, marginBottom: 8 }}>
          {title}
        </div>
        <div style={{ fontSize: 13, color: COLORS.muted, lineHeight: 1.65 }}>
          {desc}
        </div>
      </div>
    </div>
  )
}

function StatMockup() {
  const stats = [
    { label: 'CTL', value: '68', sub: 'Fitness', color: COLORS.purple },
    { label: 'ATL', value: '74', sub: 'Fatigue', color: COLORS.orange },
    { label: 'TSB', value: '-6', sub: 'Form', color: '#ff4d4d' },
    { label: 'TSS', value: '342', sub: 'This week', color: COLORS.accent },
  ]
  return (
    <div style={{
      background: COLORS.surface,
      borderTop: `1px solid ${COLORS.border}`,
      borderRight: `1px solid ${COLORS.border}`,
      borderBottom: `1px solid ${COLORS.border}`,
      borderLeft: `1px solid ${COLORS.border}`,
      borderRadius: 16,
      padding: '20px 24px',
      display: 'flex',
      gap: 0,
      position: 'relative',
      overflow: 'hidden',
    }}>
      {/* subtle glow */}
      <div style={{
        position: 'absolute', top: 0, left: 0, right: 0, height: 1,
        background: `linear-gradient(90deg, transparent, ${COLORS.accent}40, transparent)`,
      }} />
      {stats.map((s, i) => (
        <div key={s.label} style={{ flex: 1, textAlign: 'center', position: 'relative' }}>
          {i > 0 && (
            <div style={{
              position: 'absolute', left: 0, top: '10%', bottom: '10%',
              width: 1, background: COLORS.border,
            }} />
          )}
          <div style={{ fontSize: 10, color: COLORS.muted, fontWeight: 700, letterSpacing: '0.08em', textTransform: 'uppercase', marginBottom: 6 }}>
            {s.label}
          </div>
          <div style={{ fontSize: 28, fontWeight: 900, color: s.color, fontFamily: 'DM Mono, monospace', lineHeight: 1 }}>
            {s.value}
          </div>
          <div style={{ fontSize: 11, color: COLORS.muted, marginTop: 6 }}>{s.sub}</div>
        </div>
      ))}
    </div>
  )
}

function ChartMockup() {
  // Simple SVG area chart mimicking the fitness chart
  const w = 360; const h = 80
  const ctl  = [38, 42, 45, 50, 55, 58, 62, 68]
  const atl   = [30, 55, 48, 72, 60, 70, 80, 74]
  const points = (vals: number[], max: number) =>
    vals.map((v, i) => `${(i / (vals.length - 1)) * w},${h - (v / max) * h}`).join(' ')
  const max = 90

  const toPath = (vals: number[], max: number) => {
    const pts = vals.map((v, i) => ({ x: (i / (vals.length - 1)) * w, y: h - (v / max) * h }))
    return pts.map((p, i) => `${i === 0 ? 'M' : 'L'}${p.x},${p.y}`).join(' ')
  }

  const ctlPath = toPath(ctl, max)
  const atlPath = toPath(atl, max)

  return (
    <div style={{
      background: COLORS.surface,
      borderTop: `1px solid ${COLORS.border}`,
      borderRight: `1px solid ${COLORS.border}`,
      borderBottom: `1px solid ${COLORS.border}`,
      borderLeft: `1px solid ${COLORS.border}`,
      borderRadius: 16,
      padding: '16px 20px',
    }}>
      <div style={{ fontSize: 11, color: COLORS.muted, fontWeight: 700, letterSpacing: '0.08em', textTransform: 'uppercase', marginBottom: 12 }}>
        Fitness · Fatigue · Form
      </div>
      <svg viewBox={`0 0 ${w} ${h}`} style={{ width: '100%', height: 'auto', display: 'block' }} preserveAspectRatio="none">
        <defs>
          <linearGradient id="lp-ctl" x1="0" y1="0" x2="0" y2="1">
            <stop offset="0%" stopColor={COLORS.purple} stopOpacity="0.35" />
            <stop offset="100%" stopColor={COLORS.purple} stopOpacity="0.02" />
          </linearGradient>
          <linearGradient id="lp-atl" x1="0" y1="0" x2="0" y2="1">
            <stop offset="0%" stopColor={COLORS.orange} stopOpacity="0.25" />
            <stop offset="100%" stopColor={COLORS.orange} stopOpacity="0.02" />
          </linearGradient>
        </defs>
        <path d={`${ctlPath} L${w},${h} L0,${h} Z`} fill="url(#lp-ctl)" />
        <path d={ctlPath} fill="none" stroke={COLORS.purple} strokeWidth="2" />
        <path d={`${atlPath} L${w},${h} L0,${h} Z`} fill="url(#lp-atl)" />
        <path d={atlPath} fill="none" stroke={COLORS.orange} strokeWidth="2" />
      </svg>
      <div style={{ display: 'flex', gap: 16, marginTop: 10 }}>
        {[['CTL', COLORS.purple], ['ATL', COLORS.orange], ['TSB', COLORS.green]].map(([label, color]) => (
          <div key={label} style={{ display: 'flex', alignItems: 'center', gap: 5 }}>
            <div style={{ width: 8, height: 8, borderRadius: '50%', background: color }} />
            <span style={{ fontSize: 11, color: COLORS.muted }}>{label}</span>
          </div>
        ))}
      </div>
    </div>
  )
}

export function Landing() {
  const navigate = useNavigate()
  const isMobile = useIsMobile()

  return (
    <div style={{
      minHeight: '100vh',
      background: COLORS.bg,
      color: COLORS.text,
      fontFamily: "'Inter', 'Helvetica Neue', sans-serif",
      overflowX: 'hidden',
    }}>

      {/* Nav */}
      <nav style={{
        display: 'flex', alignItems: 'center', justifyContent: 'space-between',
        padding: isMobile ? '16px 20px' : '20px 48px',
        borderBottom: `1px solid ${COLORS.border}`,
        position: 'sticky', top: 0, zIndex: 10,
        background: `${COLORS.bg}ee`,
        backdropFilter: 'blur(12px)',
      }}>
        <span style={{
          fontSize: 20, fontWeight: 900, letterSpacing: '-0.04em',
          color: COLORS.text,
        }}>
          VE<span style={{ color: COLORS.accent }}>X</span>R
        </span>
        <div style={{ display: 'flex', alignItems: 'center', gap: 12 }}>
          <a
            href={GITHUB_URL}
            target="_blank"
            rel="noreferrer"
            style={{
              fontSize: 13, fontWeight: 600, color: COLORS.muted,
              textDecoration: 'none',
              padding: '7px 14px',
              borderTop: `1px solid ${COLORS.border}`,
              borderRight: `1px solid ${COLORS.border}`,
              borderBottom: `1px solid ${COLORS.border}`,
              borderLeft: `1px solid ${COLORS.border}`,
              borderRadius: 8,
            }}
          >
            GitHub ↗
          </a>
          <button
            onClick={() => navigate('/login')}
            style={{
              fontSize: 13, fontWeight: 700, color: '#000',
              background: COLORS.accent,
              border: 'none',
              borderRadius: 8,
              padding: '7px 16px',
              cursor: 'pointer',
            }}
          >
            Try the App →
          </button>
        </div>
      </nav>

      {/* Hero */}
      <section style={{
        padding: isMobile ? '64px 24px 48px' : '100px 48px 80px',
        maxWidth: 900,
        margin: '0 auto',
        textAlign: 'center',
        position: 'relative',
      }}>
        {/* Background glow */}
        <div style={{
          position: 'absolute', top: 0, left: '50%', transform: 'translateX(-50%)',
          width: 600, height: 300, borderRadius: '50%',
          background: `radial-gradient(ellipse, ${COLORS.accent}12 0%, transparent 70%)`,
          pointerEvents: 'none',
        }} />

        <div style={{
          display: 'inline-block',
          fontSize: 11, fontWeight: 700, letterSpacing: '0.12em',
          textTransform: 'uppercase', color: COLORS.accent,
          borderTop: `1px solid ${COLORS.accent}40`,
          borderRight: `1px solid ${COLORS.accent}40`,
          borderBottom: `1px solid ${COLORS.accent}40`,
          borderLeft: `1px solid ${COLORS.accent}40`,
          borderRadius: 20,
          padding: '4px 14px',
          marginBottom: 28,
        }}>
          Portfolio Project · Full-Stack SaaS
        </div>

        <h1 style={{
          fontSize: isMobile ? 40 : 68,
          fontWeight: 900,
          letterSpacing: '-0.04em',
          lineHeight: 1.05,
          margin: '0 0 24px',
          color: COLORS.text,
        }}>
          Endurance training analytics,{' '}
          <span style={{ color: COLORS.accent }}>built from scratch</span>
        </h1>

        <p style={{
          fontSize: isMobile ? 15 : 18,
          color: COLORS.muted,
          lineHeight: 1.7,
          maxWidth: 600,
          margin: '0 auto 40px',
        }}>
          Vexr is a full-stack TrainingPeaks-style platform for triathletes and endurance athletes — with a PMC fitness engine, AI coaching via Claude, Strava sync, structured workout builder, and training plan import.
        </p>

        <div style={{ display: 'flex', gap: 12, justifyContent: 'center', flexWrap: 'wrap', marginBottom: 48 }}>
          <button
            onClick={() => navigate('/login')}
            style={{
              padding: '13px 28px', fontSize: 15, fontWeight: 700,
              background: COLORS.accent, color: '#000',
              border: 'none', borderRadius: 10, cursor: 'pointer',
            }}
          >
            Try the App →
          </button>
          <a
            href={GITHUB_URL}
            target="_blank"
            rel="noreferrer"
            style={{
              padding: '13px 28px', fontSize: 15, fontWeight: 700,
              background: 'transparent', color: COLORS.text,
              borderTop: `1px solid ${COLORS.border}`,
              borderRight: `1px solid ${COLORS.border}`,
              borderBottom: `1px solid ${COLORS.border}`,
              borderLeft: `1px solid ${COLORS.border}`,
              borderRadius: 10, cursor: 'pointer',
              textDecoration: 'none', display: 'inline-block',
            }}
          >
            View Source ↗
          </a>
        </div>

        {/* Tech pill strip */}
        <div style={{ display: 'flex', gap: 8, justifyContent: 'center', flexWrap: 'wrap' }}>
          {techStack.map(t => (
            <span key={t} style={{
              fontSize: 12, fontWeight: 600, color: COLORS.muted,
              background: COLORS.surface,
              borderTop: `1px solid ${COLORS.border}`,
              borderRight: `1px solid ${COLORS.border}`,
              borderBottom: `1px solid ${COLORS.border}`,
              borderLeft: `1px solid ${COLORS.border}`,
              borderRadius: 6,
              padding: '4px 10px',
            }}>
              {t}
            </span>
          ))}
        </div>
      </section>

      {/* Dashboard preview mockup */}
      <section style={{
        padding: isMobile ? '0 20px 64px' : '0 48px 80px',
        maxWidth: 860,
        margin: '0 auto',
      }}>
        <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
          <StatMockup />
          <ChartMockup />
        </div>
        <div style={{ textAlign: 'center', marginTop: 14 }}>
          <span style={{ fontSize: 12, color: COLORS.muted }}>
            Live preview — metrics rendered from real Supabase data
          </span>
        </div>
      </section>

      {/* Features */}
      <section style={{
        padding: isMobile ? '48px 20px' : '80px 48px',
        maxWidth: 1100,
        margin: '0 auto',
      }}>
        <div style={{ textAlign: 'center', marginBottom: 48 }}>
          <div style={{ fontSize: 11, color: COLORS.muted, fontWeight: 700, letterSpacing: '0.1em', textTransform: 'uppercase', marginBottom: 12 }}>
            What's inside
          </div>
          <h2 style={{ fontSize: isMobile ? 28 : 38, fontWeight: 900, letterSpacing: '-0.03em', margin: 0 }}>
            Every feature built end-to-end
          </h2>
        </div>

        <div style={{
          display: 'grid',
          gridTemplateColumns: isMobile ? '1fr' : 'repeat(3, 1fr)',
          gap: 16,
        }}>
          {features.map(f => (
            <FeatureCard key={f.title} {...f} isMobile={isMobile} />
          ))}
        </div>
      </section>

      {/* Architecture callout */}
      <section style={{
        padding: isMobile ? '48px 20px' : '80px 48px',
        maxWidth: 860,
        margin: '0 auto',
      }}>
        <div style={{
          background: COLORS.surface,
          borderTop: `1px solid ${COLORS.border}`,
          borderRight: `1px solid ${COLORS.border}`,
          borderBottom: `1px solid ${COLORS.border}`,
          borderLeft: `1px solid ${COLORS.border}`,
          borderRadius: 16,
          padding: isMobile ? '28px 24px' : '40px 44px',
        }}>
          <div style={{ fontSize: 11, color: COLORS.muted, fontWeight: 700, letterSpacing: '0.1em', textTransform: 'uppercase', marginBottom: 16 }}>
            Architecture
          </div>
          <h3 style={{ fontSize: isMobile ? 22 : 28, fontWeight: 800, letterSpacing: '-0.03em', margin: '0 0 16px' }}>
            Production-quality patterns throughout
          </h3>
          <div style={{ fontSize: 14, color: COLORS.muted, lineHeight: 1.75, display: 'flex', flexDirection: 'column', gap: 10 }}>
            {[
              "Supabase Edge Functions with manual ES256 JWT verification — Supabase's runtime only supports HS256, so auth is enforced inside each handler via Bearer token check + supabase.auth.getUser().",
              'Code-split React with lazy() + Suspense across all pages. Manual Vite manualChunks splits vendor-react, vendor-supabase, and vendor-charts. Main bundle reduced from 962KB → 33KB.',
              'Full RLS on every Supabase table. React Error Boundary at the root. Per-user API rate limiting on Strava and Anthropic edge functions. 30s AbortController timeouts on all external fetch calls.',
              'Mobile-first responsive layout using a JS-driven useIsMobile hook — no media queries, no Tailwind. Every breakpoint handled via inline styles.',
            ].map((point, i) => (
              <div key={i} style={{ display: 'flex', gap: 12, alignItems: 'flex-start' }}>
                <span style={{ color: COLORS.accent, flexShrink: 0, marginTop: 2 }}>→</span>
                <span>{point}</span>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA */}
      <section style={{
        padding: isMobile ? '48px 20px 80px' : '80px 48px 100px',
        textAlign: 'center',
      }}>
        <h2 style={{ fontSize: isMobile ? 28 : 40, fontWeight: 900, letterSpacing: '-0.03em', margin: '0 0 16px' }}>
          See it in action
        </h2>
        <p style={{ fontSize: 15, color: COLORS.muted, margin: '0 0 32px' }}>
          Sign up with an email address and start logging workouts instantly.
        </p>
        <div style={{ display: 'flex', gap: 12, justifyContent: 'center', flexWrap: 'wrap' }}>
          <button
            onClick={() => navigate('/signup')}
            style={{
              padding: '13px 32px', fontSize: 15, fontWeight: 700,
              background: COLORS.accent, color: '#000',
              border: 'none', borderRadius: 10, cursor: 'pointer',
            }}
          >
            Create Account →
          </button>
          <button
            onClick={() => navigate('/login')}
            style={{
              padding: '13px 32px', fontSize: 15, fontWeight: 700,
              background: 'transparent', color: COLORS.text,
              borderTop: `1px solid ${COLORS.border}`,
              borderRight: `1px solid ${COLORS.border}`,
              borderBottom: `1px solid ${COLORS.border}`,
              borderLeft: `1px solid ${COLORS.border}`,
              borderRadius: 10, cursor: 'pointer',
            }}
          >
            Sign In
          </button>
        </div>
      </section>

      {/* Footer */}
      <footer style={{
        borderTop: `1px solid ${COLORS.border}`,
        padding: isMobile ? '24px 20px' : '28px 48px',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
        flexWrap: 'wrap',
        gap: 12,
      }}>
        <span style={{ fontSize: 13, color: COLORS.muted }}>
          Built by <span style={{ color: COLORS.text, fontWeight: 600 }}>Jacob Beattie</span>
        </span>
        <div style={{ display: 'flex', gap: 20, alignItems: 'center' }}>
          <a href={GITHUB_URL} target="_blank" rel="noreferrer"
            style={{ fontSize: 13, color: COLORS.muted, textDecoration: 'none' }}>
            GitHub ↗
          </a>
          <button
            onClick={() => navigate('/login')}
            style={{ fontSize: 13, color: COLORS.accent, background: 'none', border: 'none', cursor: 'pointer', fontWeight: 600, padding: 0 }}
          >
            Try the App →
          </button>
        </div>
      </footer>
    </div>
  )
}
